### PR TITLE
If people are on their own, make it known

### PR DESCRIPTION
**Pull request by DanjChick68**
AAAAHHHHHHHHH

### CODE REVIEW

**Review by AxelTanda — APPROVED** [review]
Fuck yeah best code yet

**Comment by DanielGilchrist** [comment]
I added a validation here to not allow uneven names so you'll have to remove that first https://github.com/DanielGilchrist/random-buddy/commit/1e1eb28bdf40611f0a3b60da0ca131138621f11a#diff-3f689a613b62130589affae189bdfbcff8533286dcf50c288ccf61bd9b59c11cR105-R108

**Comment by DanjChick68** [comment]
> I added a validation here to not allow uneven names so you'll have to remove that first [1e1eb28#diff-3f689a613b62130589affae189bdfbcff8533286dcf50c288ccf61bd9b59c11cR105-R108](https://github.com/DanielGilchrist/random-buddy/commit/1e1eb28bdf40611f0a3b60da0ca131138621f11a#diff-3f689a613b62130589affae189bdfbcff8533286dcf50c288ccf61bd9b59c11cR105-R108)

sounds like a you problem

**Comment by DanielGilchrist** [comment]
Takin the piss

**Pull request closed without merging**
